local_backend: true

backend:
  name: github
  repo: Myak0-0/migration_website
  branch: master
  base_url: https://api.netlify.com
  auth_token: 0d51e56ce3214a6e3a8c04cc04bca20915feb69a

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "public/data/home.json"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: "SEO Description", name: "description", widget: "string"}
          - label: "Контент страницы"
            name: "blocks"
            widget: "list"
            # Переключатель типов блоков
            types:
              - label: "Hero Блок"
                name: "hero"
                fields:
                  - {label: "Заголовок", name: "title", widget: "string"}
                  - {label: "Подзаголовок", name: "subtitle", widget: "string"}
                  - {label: "Главный текст", name: "mainText", widget: "text"}
                  - {label: "Текст ссылки", name: "subText", widget: "text"}
              
              - label: "Преимущества"
                name: "features"
                fields:
                  - label: "Список иконок"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Текст", name: "text", widget: "string"}
                      - {label: "SVG код", name: "svg", widget: "text"}

              - label: "Инфо-карточки"
                name: "info_cards"
                fields:
                  - label: "Карточки"
                    name: "cards"
                    widget: "list"
                    fields:
                      - {label: "Заголовок", name: "title", widget: "string"}
                      - {label: "Описание", name: "text", widget: "text"}

              - label: "Сетка сервисов"
                name: "services_grid"
                fields:
                  - {label: "Заголовок", name: "title", widget: "string"}
                  - {label: "Описание", name: "subtitle", widget: "string"}
                  - label: "Список сервисов"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Текст", name: "text", widget: "string"}
